//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaMVC.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoCursos
    {
        public System.Guid IDAlumnoCursos { get; set; }
        public System.Guid IDAlumno { get; set; }
        public System.Guid IDCursos { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Cursos Cursos { get; set; }
    }
}
