//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaMVC.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public System.Guid IDHorario { get; set; }
        public string Nombre { get; set; }
        public string Descripcionlarga { get; set; }
    }
}
